AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a VPC with Flow Logs enabled, sending logs to CloudWatch.

Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
  Subnet1CidrBlock:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for the first subnet
  Subnet2CidrBlock:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for the second subnet
  FlowLogsLogGroupName:
    Type: String
    Default: /aws/vpc/flowlogs
    Description: Name of the CloudWatch Logs group for VPC Flow Logs

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-Flow-Logs

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet1CidrBlock
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: Subnet1-Public

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet2CidrBlock
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: Subnet2-Public

  FlowLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FlowLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${FlowLogsLogGroupName}:*

  FlowLogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref FlowLogsLogGroupName
      RetentionInDays: 14

  VPCFlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL
      LogDestinationType: cloud-watch-logs
      LogGroupName: !Ref FlowLogsLogGroupName
      DeliverLogsPermissionArn: !GetAtt FlowLogsRole.Arn
      MaxAggregationInterval: 600
      Tags:
        - Key: Name
          Value: VPC-Flow-Logs

Outputs:
  VpcId:
    Description: ID of the created VPC
    Value: !Ref VPC
  Subnet1Id:
    Description: ID of the first subnet
    Value: !Ref Subnet1
  Subnet2Id:
    Description: ID of the second subnet
    Value: !Ref Subnet2
  FlowLogsLogGroup:
    Description: Name of the CloudWatch Logs group for Flow Logs
    Value: !Ref FlowLogsLogGroupName